services:
  - type: web
    name: keystone
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true